### ISSUE TITLE
Error Installing with PIP

### ISSUE THREAD

**Issue by KPxto** [amphinicy/marine-traffic-client-api#46]
I tried to install lib (python -m pip install Marine-Traffic-API) and see what I got. Does anybody know how to solve this?

<img width="960" alt="errorpng" src="https://user-images.githubusercontent.com/42779734/58105925-a80d7380-7bbd-11e9-8a3b-7ffcd5f5829d.png">

**Comment by arrrlo** [comment]
Hi KPxo,

Error says that you are missing Visual C++ 14.0. Please read the error message in red.
